
package the_hope;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


public class AllStudents extends javax.swing.JFrame {

    /**
     * Creates new form AllStudents
     */
    public AllStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allStu = new javax.swing.JTable();
        sort = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sort_name = new javax.swing.JMenuItem();
        sort_sID = new javax.swing.JMenuItem();
        group = new javax.swing.JMenu();
        group_class = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALL STUDENTS");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        allStu.setBackground(new java.awt.Color(204, 255, 204));
        allStu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        allStu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Birth date", "Address", "Telephone", "Class", "Parent"
            }
        ));
        jScrollPane2.setViewportView(allStu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        sort.setBackground(new java.awt.Color(204, 204, 255));
        sort.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Sort");

        sort_name.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.META_DOWN_MASK));
        sort_name.setText("Sort By Name");
        sort_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_nameActionPerformed(evt);
            }
        });
        jMenu1.add(sort_name);

        sort_sID.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.META_DOWN_MASK));
        sort_sID.setText("Sort By Student ID");
        sort_sID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_sIDActionPerformed(evt);
            }
        });
        jMenu1.add(sort_sID);

        sort.add(jMenu1);

        group.setText("Group");

        group_class.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.META_DOWN_MASK));
        group_class.setText("Group by class");
        group_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_classActionPerformed(evt);
            }
        });
        group.add(group_class);

        sort.add(group);

        jMenu2.setText("Go");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.META_DOWN_MASK));
        jMenuItem1.setText("Previous Window");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        sort.add(jMenu2);

        setJMenuBar(sort);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sort_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_nameActionPerformed
        // TODO add your handling code here:
       Connection con;
        
        String url="jdbc:mysql://localhost:3306/Hope";
        String name="root";
        String pass="";

        String sql="SELECT * FROM HopeStu ORDER BY s_name ASC";
        
        try
        {
            con=DriverManager.getConnection(url,name,pass);
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet result=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)allStu.getModel();
            model.setRowCount(0);
            
            while(result.next())
            {
                model.addRow(new String[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5),result.getString(6),result.getString(7)});
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_sort_nameActionPerformed

    private void group_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_classActionPerformed
        // TODO add your handling code here:
        Connection con;
        
        String url="jdbc:mysql://localhost:3306/Hope";
        String name="root";
        String pass="";

        String sql="SELECT * FROM HopeStu ORDER BY s_class ASC";
        
        try
        {
            con=DriverManager.getConnection(url,name,pass);
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet result=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)allStu.getModel();
            model.setRowCount(0);
            
            while(result.next())
            {
                model.addRow(new String[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5),result.getString(6),result.getString(7)});
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_group_classActionPerformed

    private void sort_sIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_sIDActionPerformed
        // TODO add your handling code here:
        Connection con;
        
        String url="jdbc:mysql://localhost:3306/Hope";
        String name="root";
        String pass="";

        String sql="SELECT * FROM HopeStu ORDER BY s_ID ASC";
        
        try
        {
            con=DriverManager.getConnection(url,name,pass);
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet result=pst.executeQuery();
            DefaultTableModel model=(DefaultTableModel)allStu.getModel();
            model.setRowCount(0);
            
            while(result.next())
            {
                model.addRow(new String[]{result.getString(1),result.getString(2),result.getString(3),result.getString(4),result.getString(5),result.getString(6),result.getString(7)});
            }
            
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_sort_sIDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Hope_Menu hm1=new Hope_Menu();
        hm1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allStu;
    private javax.swing.JMenu group;
    private javax.swing.JMenuItem group_class;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar sort;
    private javax.swing.JMenuItem sort_name;
    private javax.swing.JMenuItem sort_sID;
    // End of variables declaration//GEN-END:variables
}
